---
title: "FilmRank Vignette"
author: Nicholas Wisniewski
date: June 2, 2018
output:
  html_document:
    df_print: paged
---

<!-- 
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{LAGFFRank}
  %\usepackage[utf8]{inputenc}
-->


# Introduction

This document illustrates how to use the `FilmRank` package.

# Get IMDb Dataset

First, we get a range voting dataset from IMDb.

```{r}
require(ggplot2movies, quietly = T)
require(reshape2, quietly = T)
set.seed(137)

# get a subset of IMDb movies
movies.subgroups <- movies$year == 2003 & movies$votes < 100 & movies$votes > 10 # make some cuts
subsample.ix <- sample(1:sum(movies.subgroups), 50, replace = F) # subsample 50 films
movies.selection <- movies[movies.subgroups,][subsample.ix,]

# reshape the genre columns 
movies.melt0 <- melt(movies.selection, 
     id.vars = colnames(movies)[1:17],
     variable.name = "type", 
     value.name = "type.yes")
movies.melt <- movies.melt0[movies.melt0$type.yes == 1,]
movies.unique <- do.call(rbind, lapply(split(movies.melt, movies.melt$title), function(x) x[1,]))

# transform percentile vote columns r1-r10 into counts
movies.unique[,c(7:16)] <- round(movies.unique[,c(7:16)]/rowSums(movies.unique[,c(7:16)]) * movies.unique$votes)
```


# FilmRank Algorithm

Next, we run the `filmrank` algorithm.

```{r}
require(FilmRank, quietly = T)
suppressMessages(run <- filmrank(movies.unique, 
      title.colname = "title", 
      type.colname = "type", 
      vote.colnames = paste0("r", 1:10),
      score = function(x) mean(x, trim = 0),
      nboot = 100)
)

summary(run)
suppressMessages(plot(run, rankmetric = "authority"))
```

